baseURL = "http://guaiba.io/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
defaultContentLang = "pt-br"
paginate = 6
title = "Guaíba IO"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Sobre"
url = "#sobre"
weight = 2
[[menu.main]]
name = "Serviços"
url = "#servicos"
weight = 3
# [[menu.main]]
# name = "Projetos"
# url = "#portfolio"
# weight = 4
# [[menu.main]]
# name = "Resume"
# url = "#resume"
# weight = 5
[[menu.main]]
name = "Membros"
url = "#membros"
weight = 6
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 7
[[menu.main]]
name = "Contato"
url = "/contato"
weight = 8

# Links Menu
[[menu.sitemap]]
name = "Sobre nós"
url = "sobre"
weight = 1
[[menu.sitemap]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.sitemap]]
name = "Dúvidas Frequentes"
url = "/faq"
weight = 3
[[menu.sitemap]]
name = "Política de Privacidade"
url = "/privacidade"
weight = 4

[params]
blogPageURL = "blog"
discordLink = "contato"
copyright = "Todos os direitos autorais reservados © guaiba.io 2020"
footerLogo = "images/guaiba_io_logo_white.svg"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "G-ZWEWZKQN2N"
logo = "images/guaiba_io_logo.svg"

[params.address]
address = "Guaíba, RS."
email = "contato@guaiba.io"
openingHours = "Interação das 8h às 20h"
# phone = "(51) 987654321"

[params.map]
APIkey = ""
latitude = "-30.1274352"
longitude = "-51.3295302"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
